#ifndef GB_COMMANDIDS_H
#define GB_COMMANDIDS_H

#include <vector>

namespace Command
{
	typedef int ID;
	typedef std::vector<ID> CommandIDs;

	enum Command_IDs
	{
		NO_COMMAND,

		// APPLICATION COMMANDS
		NEW_GAME,
		QUIT_APPLICATION,
		PAUSE_GAME,
		PLAYER_DEFEATED,
		PLAYER_VICTORIOUS,

		CREATE_OBJECT_FROM_TEMPLATE_COMMAND,

		CREATE_ATTACK_COMMAND,

		// EVENTS
		ACTIVATE_COLLECTABLE_COMMAND,
		DEACTIVATE_COLLECTABLE_COMMAND,
		CLEAR_TOWER_COMMAND,
		DESTROY_OBJECT_COMMAND,
		KILL_ENTITY_COMMAND,
		PURCHASE_ENTITY_COMMAND,
		RESET_AND_ARM_TIMER_COMPONENT,
		UPDATE_PLAYER_RESOURCES_COMMAND,
		UPDATE_TEAM_RESOURCES_COMMAND,
		UPGRADE_WEAPON_COMMAND
	};

}

#endif
